Feat/kyc verification
axiomesh/axiom-tester pull request #46
Opened 2023-10-24 08:51 UTC by hyf1223

2023-10-24 09:06 UTC, ywh254 requested changes

2023-10-24 09:06 UTC, ywh254 commented on src/tests/access_tests/whitelist.test.ts
> +        const SuperUser = 1
这些const常量   放到一个文件里面吧，还有上面的

2023-10-24 09:06 UTC, ywh254 commented on src/tests/access_tests/whitelist.test.ts
> +    const Verified = 1
同下

2023-10-25 06:09 UTC, hyf1223 commented on src/tests/access_tests/whitelist.test.ts
> +        const SuperUser = 1
已修复

2023-10-25 06:09 UTC, hyf1223 commented on src/tests/access_tests/whitelist.test.ts
> +    const Verified = 1
已修复

2023-10-25 06:15 UTC, zunkk approved these changes

2023-10-25 06:15 UTC, merged